# Generated by Django 3.0.7 on 2020-06-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0002_auto_20200622_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpins',
            name='address',
            field=models.TextField(max_length=2000),
        ),
    ]
