# Generated by Django 3.0.7 on 2020-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0003_auto_20200622_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpins',
            name='image',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
