# Generated by Django 3.0.7 on 2020-06-26 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_app', '0004_savedpins_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedPins',
            new_name='SavedPin',
        ),
        migrations.CreateModel(
            name='MyTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='local_app.SavedPin')),
            ],
        ),
    ]
