# Generated by Django 3.0.7 on 2020-06-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0005_auto_20200625_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTrips',
            new_name='MyTrip',
        ),
    ]
