# Generated by Django 3.0.7 on 2020-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0007_mytrip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpin',
            name='coordinates',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
