# Generated by Django 3.0.7 on 2020-07-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0011_mytrip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrip',
            name='saved_pin',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='saved_pin',
            field=models.ManyToManyField(blank=True, to='local_app.SavedPin'),
        ),
    ]
