# Generated by Django 3.0.7 on 2020-07-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0012_auto_20200630_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrip',
            name='saved_pin',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='saved_pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='local_app.SavedPin'),
        ),
    ]
