# Generated by Django 3.0.7 on 2020-07-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0013_auto_20200630_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='saved_pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local_app.SavedPin'),
        ),
    ]
