# Generated by Django 3.0.7 on 2020-07-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_app', '0014_auto_20200703_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='saved_pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_app.SavedPin'),
        ),
    ]
