from django.urls import path
from . import views

urlpatterns = [
    path('alamosquare/', views.alamosquare, name="alamosquare"),
    path('bernalheights/', views.bernalheights, name="bernalheights"),
    path('castro/', views.castro, name="castro"),
    path('chinatown/', views.chinatown, name="chinatown"),
    path('civiccenter/', views.civiccenter, name="civiccenter"),
    path('colevalley/', views.colevalley, name="colevalley"),
    path('diamondheights/', views.diamondheights, name="diamondheights"),
    path('excelsior/', views.excelsior, name="excelsior"),
    path('filmore/', views.filmore, name="filmore"),
    path('financialdistrict/', views.financialdistrict, name="financialdistrict"),
    path('forestHills/', views.forestHills, name="forestHills"),
    path('forestknolls/', views.forestknolls, name="forestknolls"),
    path('glenpark/', views.glenpark, name="glenpark"),
    path('goldengate/', views.goldengate, name="goldengate"),
    path('haightashbury/', views.haightashbury, name="haightashbury"),
    path('hayesvalley/', views.hayesvalley, name="hayesvalley"),
    path('bayview/', views.bayview, name="bayview"),
    path('ingleside/', views.ingleside, name="ingleside"),
    path('japantown/', views.japantown, name="japantown"),
    path('lowerhaight/', views.lowerhaight, name="lowerhaight"),
    path('marina/', views.marina, name="marina"),
    path('miraloma/', views.miraloma, name="miraloma"),
    path('mission/', views.mission, name="mission"),
    path('neighborwoods/', views.neighborwoods, name="neighborwoods"),
    path('nobhill/', views.nobhill, name="nobhill"),
    path('noevalley/', views.noevalley, name="noevalley"),
    path('northbeach/', views.northbeach, name="northbeach"),
    path('oceanview/', views.oceanview, name="oceanview"),
    path('outermission/', views.outermission, name="outermission"),
    path('pacificheights/', views.pacificheights, name="pacificheights"),
    path('parkmerced/', views.parkmerced, name="parkmerced"),
    path('thepresidio/', views.thepresidio, name="thepresidio"),
    path('portrerohill/', views.portrerohill, name="portrerohill"),
    path('richmonddistrict/', views.richmonddistrict, name="richmonddistrict"),
    path('russianhill/', views.russianhill, name="russianhill"),
    path('soma/', views.soma, name="soma"),
    path('sunsetdistrict/', views.sunsetdistrict, name="sunsetdistrict"),
    path('tenderloin/', views.tenderloin, name="tenderloin"),
    path('twinpeaks/', views.twinpeaks, name="twinpeaks"),
    path('unionsquare/', views.unionsquare, name="unionsquare"),
    path('westportal/', views.westportal, name="westportal"),
    path('westernaddition/', views.westernaddition, name="westernaddition"),
]